// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
  {
  "swagger": "2.0",
  "info": {
    "description": "This is todo list management",
    "title": "Todo Application",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "name": "API Support",
      "url": "http://www.swagger.io/support",
      "email": "support@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0"
  },
  "host": "localhost:9000",
  "basePath": "/todos",
  "paths": {
    "/todos": {
      "get": {
        "description": "Menampilkan semua daftar data ToDo",
        "produces": [
          "application/json"
        ],
        "tags": [
          "todos"
        ],
        "summary": "Menampilkan semua ToDo",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/models.Todo"
              }
            }
          }
        }
      },
      "post": {
        "description": "Menambahkan satu data ToDo baru",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "todos"
        ],
        "summary": "Menambahkan ToDo Baru",
        "parameters": [
          {
            "description": "Buat Todo",
            "name": "todo",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/models.Todo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/models.Todo"
            }
          }
        }
      }
    },
    "/todos/{id}": {
      "get": {
        "description": "Menampilkan sebuah data ToDo berdasarkan Id yang dimasukkan",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "todos"
        ],
        "summary": "Menampilkan sebuah data ToDo",
        "parameters": [
          {
            "type": "integer",
            "description": "Ambil By Id",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/models.Todo"
            }
          }
        }
      },
      "put": {
        "description": "Mengubah ToDo yang sudah ada",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "todos"
        ],
        "summary": "Mengubah ToDo",
        "parameters": [
          {
            "type": "integer",
            "description": "Ubah ToDo",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "minta data json",
            "name": "todo",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/models.Todo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/models.Todo"
            }
          }
        }
      },
      "delete": {
        "description": "Menghapus ToDo yang sudah ada",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "todos"
        ],
        "summary": "Menghapus ToDo",
        "parameters": [
          {
            "type": "integer",
            "description": "Hapus ToDo",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/models.Todo"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "models.Todo": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "nama": {
          "type": "string"
        },
        "kegiatan:"{
          "type": "string"
        },
        "tanggal": {
          "type": "integer"
      }
    }
  },
  "securityDefinitions": {
    "BasicAuth": {
      "type": "basic"
    }
  }
}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9000",
	BasePath:         "/todos",
	Schemes:          []string{},
	Title:            "Todo Application",
	Description:      "This is todo list management.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
